name = "probstreet-notification-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
queue = "notification-queue"
max_batch_size = 10
max_batch_timeout = 2
max_retries = 2

[observability.logs]
enabled = true
